# Site settings
title: Jean-Christophe Bohin
email: jc [at] bohin [dot] net
description: "Entrepreneur, Technologeek, Webologist, IT Architect, Photo Enthusiast. I like innovation, chalenges, and solving problems."
baseurl: ""
url: "http://jc.bohin.net"
twitter_username: bohinjc
github_username:  jcbohin

timezone: Europe/Paris

# Build settings
markdown: kramdown
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jean-Christophe Bohin"
