# Site settings
title: Jean-Christophe Bohin
email:
description: "Entrepreneur, Technologeek, Webologist, IT Architect, Photo Enthusiast. I like innovation, chalenge, solving problems, Python and Golang. My goal is to reach simple, elegant and performant architectures."
baseurl: ""
url: "http://jcbohin.github.io"
twitter_username: bohinjc
github_username:  jcbohin

# Build settings
markdown: kramdown
permalink: pretty
